// <auto-generated />
using System;
using BlazorPizzeria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorPizzeria.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424200740_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("BlazorPizzeria.Models.Dessert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Desserts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 450,
                            Description = "Классический",
                            ImageUrl = "/images/desserts/tiramisu.jpg",
                            Name = "Тирамису",
                            Price = 380m
                        },
                        new
                        {
                            Id = 2,
                            Calories = 420,
                            Description = "Нью-Йорк",
                            ImageUrl = "/images/desserts/cheesecake.jpg",
                            Name = "Чизкейк",
                            Price = 350m
                        });
                });

            modelBuilder.Entity("BlazorPizzeria.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "0.5 л",
                            ImageUrl = "/images/drinks/coke.jpg",
                            Name = "Кока-кола",
                            Price = 150m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Домашний",
                            ImageUrl = "/images/drinks/mors.jpg",
                            Name = "Морс",
                            Price = 120m
                        },
                        new
                        {
                            Id = 3,
                            Description = "0.5 л",
                            ImageUrl = "/images/drinks/sprite.jpg",
                            Name = "Спрайт",
                            Price = 150m
                        },
                        new
                        {
                            Id = 4,
                            Description = "0.5 л",
                            ImageUrl = "/images/drinks/fanta.jpg",
                            Name = "Фанта",
                            Price = 150m
                        },
                        new
                        {
                            Id = 5,
                            Description = "0.449 л",
                            ImageUrl = "/images/drinks/adrenaline.jpg",
                            Name = "Адреналин",
                            Price = 190m
                        },
                        new
                        {
                            Id = 6,
                            Description = "0.5 л",
                            ImageUrl = "/images/drinks/water.jpg",
                            Name = "Вода",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("BlazorPizzeria.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BlazorPizzeria.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DessertId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DrinkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PizzaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DessertId");

                    b.HasIndex("DrinkId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Томатный соус, свежая моцарелла, душистый базилик, оливковое масло extra virgin.",
                            ImageUrl = "/images/pizzas/margherita.jpg",
                            IsVegetarian = true,
                            Name = "Маргарита",
                            Price = 490m,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Сливочный соус и смесь из моцареллы, пармезана, горгонзолы, фонтана.",
                            ImageUrl = "/images/pizzas/quattro_formaggi.jpg",
                            IsVegetarian = true,
                            Name = "Четыре сыра",
                            Price = 620m,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Артишоки (весна), оливки и томаты (лето), прошутто или грибы (осень), моцарелла (зима).",
                            ImageUrl = "/images/pizzas/quattro_stagioni.jpg",
                            IsVegetarian = false,
                            Name = "Четыре сезона",
                            Price = 680m,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Моцарелла, томаты, прошутто или ветчина, артишоки, шампиньоны, оливки.",
                            ImageUrl = "/images/pizzas/capricciosa.jpg",
                            IsVegetarian = false,
                            Name = "Капричоза",
                            Price = 670m,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Салями, халапеньо, томатный соус, сыр — дьявольски острая.",
                            ImageUrl = "/images/pizzas/diavola.jpg",
                            IsVegetarian = false,
                            Name = "Дьябола",
                            Price = 650m,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Курица, сыр и сочные кусочки ананаса — сладко-солёная классика.",
                            ImageUrl = "/images/pizzas/hawaiian.jpg",
                            IsVegetarian = false,
                            Name = "Гавайская",
                            Price = 610m,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Сладкий перец, цуккини, баклажаны, шампиньоны, томаты, маслины — полезно и сытно.",
                            ImageUrl = "/images/pizzas/vegetariana.jpg",
                            IsVegetarian = true,
                            Name = "Вегетарианская",
                            Price = 560m,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Закрытая пицца с рикоттой, моцареллой, прошутто или грибами в тонком хрустящем тесте.",
                            ImageUrl = "/images/pizzas/calzone.jpg",
                            IsVegetarian = false,
                            Name = "Кальцоне",
                            Price = 640m,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Вяленые томаты, пармезан, копчёная паприка — наш секретный рецепт.",
                            ImageUrl = "/images/pizzas/signature.jpg",
                            IsVegetarian = false,
                            Name = "Пицца Дон (фирменная)",
                            Price = 720m,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Прошутто крудо, пармезан, руккола, вяленые томаты, бальзамический крем.",
                            ImageUrl = "/images/pizzas/parmense.jpg",
                            IsVegetarian = false,
                            Name = "Пармская",
                            Price = 750m,
                            Size = "Medium"
                        });
                });

            modelBuilder.Entity("BlazorPizzeria.Models.OrderItem", b =>
                {
                    b.HasOne("BlazorPizzeria.Models.Dessert", "Dessert")
                        .WithMany("OrderItems")
                        .HasForeignKey("DessertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BlazorPizzeria.Models.Drink", "Drink")
                        .WithMany("OrderItems")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BlazorPizzeria.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pizza", "Pizza")
                        .WithMany("OrderItems")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dessert");

                    b.Navigation("Drink");

                    b.Navigation("Order");

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("BlazorPizzeria.Models.Dessert", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BlazorPizzeria.Models.Drink", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BlazorPizzeria.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Pizza", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
